name: "Personal Agent Compute"

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"
      signature:
        description: "The kernel signature"
      command:
        description: "Command from the Kernel"
        required: false

jobs:
  compute:
    name: "Personal Agent"
    runs-on: ubuntu-latest
    permissions: write-all
    environment: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) && 'main' || 'development' }}
    env:
      PLUGIN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL || 'info' }}
      AGENT_OWNER: ${{ github.repository_owner }}
      USER_PAT: ${{ secrets.USER_PAT }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Claude CLI
        run: |
          echo "Installing Claude CLI..."
          # Download and install the official Claude CLI
          curl -fsSL https://claude.ai/install.sh | sh
          # Add Claude to PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "Claude CLI installed successfully"

      - name: Execute Personal Agent
        run: node ./dist/index.js
        id: plugin-name
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
